name = "TidierStrings"
uuid = "248e6834-d0f8-40ef-8fbb-8e711d883e9c"
authors = ["Daniel Rizk"]
version = "0.1.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
